apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: andreaskuberneres
  name: andreaskuberneres
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: andreaskuberneres
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: andreaskuberneres
    spec:
      containers:
      - image: gcr.io/kubernetes21/kubernetesworkshop21:cf11a54d224e3b12e5be6a6ef54047c2850c5ccf
        imagePullPolicy: IfNotPresent
        name: andreaskuberneres
        ports:
        - containerPort: 9000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: andreaskuberneres
  name: andreaskuberneres
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31601
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    run: andreaskuberneres
  sessionAffinity: None
  type: LoadBalancer
